### ISSUE TITLE
error : make/make install

### ISSUE THREAD

**Issue by sravani9408** [qmarcou/IGoR#39]
1 error generated.
make[1]: *** [igor-Coverageerrcounter.o] Error 1
make: *** [install-recursive] Error 1
~~~~~~~~~~~~~~~
Hello qmarcou,
As suggested I did make clean , make and then make install. Still I am getting the same errors. Below is the log file.
[error_logs.txt](https://github.com/qmarcou/IGoR/files/2917457/error_logs.txt)

Thanks

**Comment by qmarcou** [comment]
Hi @sravani9408 ,
Could you give me a bit more information? e.g the command line you have used and the complete error log ? Which compiler are you using on which operating system?
Otherwise without more information i can only advise you to first use `make clean` and then `make` again, before `make install`
Best regards,

**Comment by sravani9408** [comment]
Hello 
I am using macOS mojave (v 10.14.3). 
I've downloaded gcc using homebrew. 

(base) M:igor_1-3-0 sv177$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... x86_64-apple-darwin13.4.0-clang
checking whether the C compiler works... no
configure: error: in `/Users/sv177/downloads/igor_1-3-0':
configure: error: C compiler cannot create executables
See `config.log' for more details
(base) M:igor_1-3-0 sv177$ make clean
make: *** No rule to make target 'clean'.  Stop.
(base) M:igor_1-3-0 sv177$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by sravani9408** [comment]
Hello qmarcou,
Could you please help me fix this error. Attached is the error log.

[error.log](https://github.com/qmarcou/IGoR/files/2920748/error.log)


Coverageerrcounter.cpp:141:19: note: in instantiation of member function
      'std::__1::unordered_map<std::__1::basic_string<char>, Event_realization,
      std::__1::hash<std::__1::basic_string<char> >,
      std::__1::equal_to<std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>,
      Event_realization> > >::operator=' requested here
                        v_realizations = v_gene_event_p->get_realizations_map();
                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/utility:325:5: note: 
      copy assignment operator is implicitly deleted because
      'pair<std::__1::basic_string<char>, Event_realization>' has a
      user-declared move constructor
    pair(pair&&) = default;
    ^
1 error generated.
make[2]: *** [igor-Coverageerrcounter.o] Error 1
mv -f .deps/igor-Errorscounter.Tpo .deps/igor-Errorscounter.Po
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by qmarcou** [comment]
Hello @sravani9408 ,
I suspect you may have missed some of the installation guidelines. Although you have edited your message I think I remember you're using MacOS and have installed gcc via brew and used `./configure`. Please have a look at the [installation manual](https://qmarcou.github.io/IGoR/#macos) stating: 

> MacOS is shipped with another compiler (Clang) when installing Xcode that is called upon calling gcc (through name aliasing) and is not supporting OpenMP. In order to use gcc and compile with it an OpenMP application you will first need to download Macports or Homebrew and install gcc from there.

and

> Note: if you decide to use Homebrew you should apparently refrain yourself from assigning the newly installed gcc to the gcc command(see this page for more details). You will thus have to pass the correct compiler instructions to the configure script with the CC and CXX flags.

and 

> Many options can be appended to ./configure such as ./configure CC=gcc CXX=g+ + to enforce the use of gcc as compiler. The full set of the configure script options can be found here.

Please remember that once you have installed GCC via Homebrew you will have to pass the correct compiler's name and version to the configure script in order to use it. Given the fact that in your error log `make` is calling `g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I..    -I./../libs/jemalloc/include/jemalloc -I./../libs/gsl_sub  -DIGOR_DATA_DIR=\"/usr/local/share/igor\" -g -O2 -MT igor-Coverageerrcounter.o -MD -MP -MF .deps/igor-Coverageerrcounter.Tpo -c -o igor-Coverageerrcounter.o `test -f 'Coverageerrcounter.cpp' || echo './'`Coverageerrcounter.cpp` I suspect by using `g++` you are still using the Clang compiler instead of gcc.

**Comment by sravani9408** [comment]
Hello @qmarcou 

Thank you so much. I used Macports(gcc 6) and append options to configure instead of homebrew and it worked.

Thanks again,
Sravani
