### ISSUE TITLE
what's the definition of model or contents of model?

### ISSUE THREAD

**Issue by decenwang** [qmarcou/IGoR#44]
Hi Quentin,

As a beginner, I have to come up with this kind of stupid question. What are the detailed contents in the model when learning? As I can, IGoR could learn from a dataset to get  all the V, D, J genes, junctions, length of CDR3, insertions and deletions information followed by -infer/evalute process. Yes, this step is fulfilled by -align. Is that right?
However, in your article and "[https://qmarcou.github.io/IGoR/]" or man -igor, there are a lot of index/indices. I am a bit confused by this universal "index", what's it? Thanks!

Best,

Decen

**Comment by qmarcou** [comment]
Dear @decenwang ,
I am not sure I understand the sense of both your questions.

I invite you to have another read at the documentation: the alignment step is a pre-processing step that enables secondly to run the inference and learn a recombination model.

As for the "index", I would again need a bit more context as there are many indices involved operations since the generic name 'index' is used in programming to denote a non negative integer designating position on an array/string/etc.

**Comment by decenwang** [comment]
> Dear @decenwang ,
> I am not sure I understand the sense of both your questions.
> 
> I invite you to have another read at the documentation: the alignment step is a pre-processing step that enables secondly to run the inference and learn a recombination model.
> 
> As for the "index", I would again need a bit more context as there are many indices involved operations since the generic na/detailme 'index' is used in programming to denote a non negative integer designating position on an array/string/etc.

Hi Quentin,

Sorry for loads of troubles for you. 
I mean, within the three modes: learning, analysis, generation, in your article, you said: In the learning mode, IGoR infers a recombination statistics of large data sets of sequences ......., I would like to know what is the meaning/details of the recombination statistics?
for the second, Now I got it. thanks  a lot!
Anyway, this is my last question. 

Best,

Decen
