### ISSUE TITLE
Compilation issue with Mac OS Mojave

### ISSUE THREAD

**Issue by jdgagnon** [qmarcou/IGoR#45]
I am having trouble compiling IGoR on my Mac running macOS Mojave 10.14.3 

```
$ ./configure CC=/usr/local/Cellar/gcc/7.3.0_1/bin/gcc-7 CXX=/usr/local/Cellar/gcc/7.3.0_1/bin/g++-7
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /usr/local/Cellar/gcc/7.3.0_1/bin/gcc-7
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/jgagnon/igor_1-3-0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

I am trying to use gcc-7 based on a prior issue I saw regarding gcc-8 but I am getting a different error. Attached is the log.

Thanks for your help!

[config.log](https://github.com/qmarcou/IGoR/files/3026876/config.log)

**Comment by jdgagnon** [comment]
Just installed gcc@7 (which is version 7.4) and compiled successfully. Must have been something about version 7.3 with Mojave maybe?

**Comment by qmarcou** [comment]
Hi @jdgagnon ,
Glad you found a workaround! I'm not sure what the error meant in a first place, this [post](https://stackoverflow.com/questions/31943461/configure-error-cannot-run-c-compiled-programs) suggests your computer was trying to compile for another architecture than macos (see how the problem was solved by specifying the host in the previous post), maybe there was an issue upon installing gcc in a first place.
Anyway, glad you solved it
