### ISSUE TITLE
Errors: python to parse the output results?

### ISSUE THREAD

**Issue by decenwang** [qmarcou/IGoR#48]
Hi @qmarcou 

I have installed the pygor by your command line. when I tried to use the submodule: pygor to dispaly the result. igor reported an error:
`decen@bio:~/Downloads/seq/igor/foo3_output$ igor -pygor best_scenarios_counts.csv 
[IGoR] ERROR: Unknown IGoR command line argument "-pygor" 
[IGoR] ERROR: Use "man igor", "igor -help" or visit https://github.com/qmarcou/IGoR to see available commands and their effects.
[IGoR] ERROR: Please report any bug by opening an issue on https://github.com/qmarcou/IGoR or email: quentin.marcou@lpt.ens.fr
[IGoR] ERROR: Terminating IGoR...
`
the "-pygor" cannot be recognized.
If I run independently as the below command:
`. /home/decen/packages/igor_1-3-0/pygor/pygor/counters/bestscenarios/bestscenarios.py csv.file`
it also show errors:
` 
from: can't read /var/mail/...models.genmodel
from: can't read /var/mail/...utils
bash: /home/decen/packages/igor_1-3-0/pygor/pygor/counters/bestscenarios/bestscenarios.py: line 32: syntax error near unexpected token `('
bash: /home/decen/packages/igor_1-3-0/pygor/pygor/counters/bestscenarios/bestscenarios.py: line 32: `def read_bestscenarios_values(scenarios_file, model_parms_file):'
`

Could you please help this ?

Thanks a lot!

Best,

Decen

**Comment by decenwang** [comment]
` decen@bio:~/packages/igor_1-3-0/pygor/pygor/counters/bestscenarios$ /home/decen/software/miniconda/bin/python3.7 bestscenarios.py 
Traceback (most recent call last):
  File "bestscenarios.py", line 28, in <module>
    from ...models.genmodel import GenModel
ValueError: attempted relative import beyond top-level package
`

**Comment by qmarcou** [comment]
Dear @decenwang ,
The pygor module is here to help you deal with IGoR I/O in your own python scripts or within an interactive Python interpreter session, it cannot be directly executed as a Python script. You can import the module once installed via pip, and use it within Python. I invite you to read a short Python tutorial in order to use pygor. We might supply an easier interface in a short while but for now this is it.

I would also kindly ask you to refrain from multi-posting since maintaining the software and answering users question is already time consuming and duplicating your posts is only distracting and making us waste time. I have thus deleted your duplicated questions within the various unrelated issues, in order to keep clear answers for other users. I would also like to remind you that IGoR's under GNU-GPLv3 license, and although we are happy to provide as much help as we can to IGoR users, IGoR comes without any warranty and we are not liable for any issue you might have with IGoR.

Best regards,
